language: minimal
env:
  - TASK_VERSION=v2.4.0
  - TASK_VERSION=v2.4.1
  - TASK_VERSION=v2.4.2
  - TASK_VERSION=v2.4.3
  - TASK_VERSION=v2.4.4
  - TASK_VERSION=v2.5.0
  - TASK_VERSION=v2.5.1
services:
  - docker
install:
  # Build the docker container
  - pushd $TRAVIS_BUILD_DIR
  - docker-compose build --build-arg TASK_VERSION=$TASK_VERSION tests
script:
  - make test
