version: '3'
services:
  tests:
    build: .
    volumes:
      - ".:/root/.vim/bundle/taskwiki:ro"
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
    command: xvfb-run --server-args=-noreset python3 -m pytest -o cache_dir=/tmp/pytest-cache -vv $PYTEST_FLAGS tests/
